# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "bogDown"

on:
  issues:
    types: [opened]

jobs:
  shake:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.7]
    if: startsWith(github.event.issue.title, 'shake')
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set env vars
      run: |
        echo ::set-env name=REPOSITORY::${{ github.repository }}
        echo ::set-env name=EVENT_ISSUE_NUMBER::${{ github.event.issue.number }}
        echo ::set-env name=EVENT_USER_LOGIN::${{ github.event.issue.user.login }}
        echo ::set-env name=EVENT_ISSUE_COMMENT::"${{ github.event.issue.body }}"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Shake
      run: |
        echo ${EVENT_ISSUE_COMMENT}
        python -c "import os, boggle; boggle.Board().play_github(user_words=os.environ['EVENT_ISSUE_COMMENT'])"
